version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  node: circleci/node@1.1.6

references:
  workspace_root: &workspace_root /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  static-code-analysis:
    docker:
      - image: "node:8.17"
    steps:
      - *attach_workspace
      - sonarcloud/scan

  build-and-test:
    executor:
      name: node/default
    steps:
      - *attach_workspace
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

workflows:
  checks:
    jobs:
      - build-and-test
      - static-code-analysis:
          context: SonarCloud
          requires:
            - build-and-test
