version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  node: circleci/node@1.1.6

jobs:
  static-code-analysis:
    docker:
      - image: "node:8.17"
    steps:
      - sonarcloud/scan

  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            # - run: npm test
workflows:
  checks:
    jobs:
      - build-and-test
      - static-code-analysis:
          context: SonarCloud